baseURL = "https://mouthless-mutters.github.io/blog/"
languageCode = "en-us"
title = "Mouthless Mutters"
theme = "ananke"

# Pagination
[pagination]
  pagerSize = 10

[params]
  description = "Notes on things I feel like writing about."
  author = "Jake"
  show_reading_time = true
