baseURL = "https://mouthless-mutters.github.io/blog/"
languageCode = "en-us"
title = "Mouthless Mutters"
theme = "ananke"

[pagination]
  pagerSize = 10

[params]
  description = "Notes on grappling, cyber security, and tech."
  author = "Jake"
  show_reading_time = true
